export interface Product {
  id: string;
  name: string;
  category: string;
  price: number;
  description: string;
  image: string;
  nutrition: {
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
  };
  tags: string[];
  inStock: boolean;
}

export interface OrderItem {
  product: Product;
  quantity: number;
}

// Mock product images - Using more realistic images
const productImages = [
  "https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?q=80&w=300&auto=format", // avocado
  "https://images.unsplash.com/photo-1563636619-e9143da7973b?q=80&w=300&auto=format", // almond milk
  "https://images.unsplash.com/photo-1598373182133-52452f7691ef?q=80&w=300&auto=format", // bread
  "https://images.unsplash.com/photo-1598965402089-897e8f8db0c3?q=80&w=300&auto=format", // eggs
  "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=300&auto=format", // salmon
  "https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=300&auto=format", // spinach
  "https://images.unsplash.com/photo-1571211905393-6de67ff8fb61?q=80&w=300&auto=format", // greek yogurt
  "https://images.unsplash.com/photo-1586201375761-83865001e8ac?q=80&w=300&auto=format", // quinoa
  "https://images.unsplash.com/photo-1599488876865-ef82efdef257?q=80&w=300&auto=format", // turmeric
  "https://images.unsplash.com/photo-1599789197514-47270cd526b4?q=80&w=300&auto=format", // rice
  "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=300&auto=format", // lentils
  "https://images.unsplash.com/photo-1599789392889-5fd7d2b025e6?q=80&w=300&auto=format", // ghee
  "https://images.unsplash.com/photo-1528712306091-ed0763094c98?q=80&w=300&auto=format", // coconut oil
  "https://images.unsplash.com/photo-1626895272551-ad33e374a7fa?q=80&w=300&auto=format", // coriander
  "https://images.unsplash.com/photo-1620574387735-3624d75b2dbc?q=80&w=300&auto=format", // cumin
  "https://images.unsplash.com/photo-1590301157890-4810ed352733?q=80&w=300&auto=format", // tea
];

// Generate sample products
export const products: Product[] = [
  {
    id: "p001",
    name: "Organic Avocado",
    category: "Produce",
    price: 120,
    description: "Fresh organic avocados, perfect for guacamole or toast.",
    image: productImages[0],
    nutrition: {
      calories: 240,
      protein: 3,
      carbs: 12,
      fat: 22,
    },
    tags: ["organic", "fruit", "healthy", "fresh"],
    inStock: true,
  },
  {
    id: "p002",
    name: "Almond Milk",
    category: "Dairy & Alternatives",
    price: 165,
    description: "Unsweetened almond milk, great alternative to dairy milk.",
    image: productImages[1],
    nutrition: {
      calories: 30,
      protein: 1,
      carbs: 1,
      fat: 2.5,
    },
    tags: ["vegan", "milk", "dairy-free", "unsweetened"],
    inStock: true,
  },
  {
    id: "p003",
    name: "Whole Grain Bread",
    category: "Bakery",
    price: 45,
    description: "Freshly baked whole grain bread, high in fiber.",
    image: productImages[2],
    nutrition: {
      calories: 80,
      protein: 4,
      carbs: 15,
      fat: 1,
    },
    tags: ["whole grain", "bread", "bakery", "fiber"],
    inStock: true,
  },
  {
    id: "p004",
    name: "Free-Range Eggs",
    category: "Dairy & Alternatives",
    price: 90,
    description: "One dozen free-range eggs from local farms.",
    image: productImages[3],
    nutrition: {
      calories: 70,
      protein: 6,
      carbs: 0,
      fat: 5,
    },
    tags: ["protein", "eggs", "free-range", "organic"],
    inStock: true,
  },
  {
    id: "p005",
    name: "Atlantic Salmon Fillet",
    category: "Meat & Seafood",
    price: 575,
    description: "Fresh wild-caught Atlantic salmon fillet.",
    image: productImages[4],
    nutrition: {
      calories: 208,
      protein: 22,
      carbs: 0,
      fat: 13,
    },
    tags: ["fish", "protein", "seafood", "omega-3"],
    inStock: true,
  },
  {
    id: "p006",
    name: "Organic Spinach",
    category: "Produce",
    price: 40,
    description: "Fresh organic baby spinach, pre-washed and ready to eat.",
    image: productImages[5],
    nutrition: {
      calories: 23,
      protein: 2.9,
      carbs: 3.6,
      fat: 0.4,
    },
    tags: ["organic", "vegetables", "leafy greens", "salad"],
    inStock: true,
  },
  {
    id: "p007",
    name: "Greek Yogurt",
    category: "Dairy & Alternatives",
    price: 95,
    description: "Plain Greek yogurt, high in protein and probiotics.",
    image: productImages[6],
    nutrition: {
      calories: 100,
      protein: 17,
      carbs: 6,
      fat: 0,
    },
    tags: ["dairy", "yogurt", "protein", "probiotics"],
    inStock: true,
  },
  {
    id: "p008",
    name: "Quinoa",
    category: "Grains",
    price: 140,
    description: "Organic white quinoa, a complete protein grain.",
    image: productImages[7],
    nutrition: {
      calories: 120,
      protein: 4,
      carbs: 21,
      fat: 1.8,
    },
    tags: ["grain", "protein", "gluten-free", "organic"],
    inStock: true,
  },
  {
    id: "p009",
    name: "Basmati Rice",
    category: "Staples",
    price: 125,
    description: "Premium long-grain aromatic basmati rice from the foothills of the Himalayas.",
    image: productImages[9],
    nutrition: {
      calories: 130,
      protein: 3,
      carbs: 28,
      fat: 0,
    },
    tags: ["rice", "staple", "indian", "grains"],
    inStock: true,
  },
  {
    id: "p010",
    name: "Toor Dal (Yellow Split Pigeon Peas)",
    category: "Pulses",
    price: 90,
    description: "Premium quality toor dal, essential for making sambar and other lentil dishes.",
    image: productImages[10],
    nutrition: {
      calories: 110,
      protein: 7,
      carbs: 19,
      fat: 0.4,
    },
    tags: ["dal", "lentils", "protein", "indian", "pulses"],
    inStock: true,
  },
  {
    id: "p011",
    name: "Turmeric Powder",
    category: "Spices",
    price: 55,
    description: "Organic turmeric powder with high curcumin content for vibrant color and health benefits.",
    image: productImages[8],
    nutrition: {
      calories: 9,
      protein: 0.3,
      carbs: 1.4,
      fat: 0.2,
    },
    tags: ["spices", "indian", "organic", "turmeric"],
    inStock: true,
  },
  {
    id: "p012",
    name: "Garam Masala",
    category: "Spices",
    price: 65,
    description: "Aromatic blend of ground spices used in Indian cuisine including cardamom, cinnamon, and cloves.",
    image: productImages[14],
    nutrition: {
      calories: 8,
      protein: 0.4,
      carbs: 1.5,
      fat: 0.4,
    },
    tags: ["spices", "indian", "blend", "aromatic"],
    inStock: true,
  },
  {
    id: "p013",
    name: "Pure Cow Ghee",
    category: "Dairy & Alternatives",
    price: 320,
    description: "Traditional clarified butter made from pure cow's milk, ideal for cooking and religious rituals.",
    image: productImages[11],
    nutrition: {
      calories: 120,
      protein: 0,
      carbs: 0,
      fat: 14,
    },
    tags: ["dairy", "ghee", "indian", "cooking"],
    inStock: true,
  },
  {
    id: "p014",
    name: "Mustard Seeds",
    category: "Spices",
    price: 30,
    description: "Black mustard seeds essential for tempering in South Indian dishes.",
    image: productImages[14],
    nutrition: {
      calories: 5,
      protein: 0.3,
      carbs: 0.6,
      fat: 0.3,
    },
    tags: ["spices", "indian", "seeds", "tempering"],
    inStock: true,
  },
  {
    id: "p015",
    name: "Fresh Coriander (Dhania)",
    category: "Produce",
    price: 15,
    description: "Fresh coriander leaves, essential garnish for Indian dishes and chutneys.",
    image: productImages[13],
    nutrition: {
      calories: 5,
      protein: 0.5,
      carbs: 0.9,
      fat: 0.1,
    },
    tags: ["herbs", "fresh", "garnish", "indian"],
    inStock: true,
  },
  {
    id: "p016",
    name: "Coconut Oil",
    category: "Oils & Condiments",
    price: 185,
    description: "Cold-pressed virgin coconut oil, perfect for South Indian cooking.",
    image: productImages[12],
    nutrition: {
      calories: 120,
      protein: 0,
      carbs: 0,
      fat: 14,
    },
    tags: ["oil", "cooking", "indian", "organic"],
    inStock: true,
  },
  {
    id: "p017",
    name: "Premium Darjeeling Tea",
    category: "Beverages",
    price: 135,
    description: "Fine loose-leaf Darjeeling tea from the foothills of the Himalayas.",
    image: productImages[15],
    nutrition: {
      calories: 2,
      protein: 0,
      carbs: 0.4,
      fat: 0,
    },
    tags: ["tea", "beverages", "indian", "organic"],
    inStock: true,
  },
  {
    id: "p018",
    name: "Chana Dal (Split Bengal Gram)",
    category: "Pulses",
    price: 70,
    description: "Split chickpea lentils, perfect for dal preparations and South Indian dishes.",
    image: productImages[10],
    nutrition: {
      calories: 120,
      protein: 8,
      carbs: 22,
      fat: 1,
    },
    tags: ["dal", "lentils", "protein", "indian", "pulses"],
    inStock: true,
  },
  {
    id: "p019",
    name: "Sona Masoori Rice",
    category: "Staples",
    price: 110,
    description: "Medium-grain rice popular in South Indian cuisine, known for its light and fluffy texture.",
    image: productImages[9],
    nutrition: {
      calories: 130,
      protein: 2.7,
      carbs: 28,
      fat: 0.3,
    },
    tags: ["rice", "staple", "indian", "grains"],
    inStock: true,
  },
  {
    id: "p020",
    name: "Wheat Flour (Atta)",
    category: "Staples",
    price: 85,
    description: "Stone-ground whole wheat flour for making chapatis, rotis, and parathas.",
    image: productImages[9],
    nutrition: {
      calories: 110,
      protein: 4,
      carbs: 22,
      fat: 0.5,
    },
    tags: ["flour", "staple", "indian", "baking"],
    inStock: true,
  },
  {
    id: "p021",
    name: "Rava/Sooji (Semolina)",
    category: "Staples",
    price: 60,
    description: "Coarse wheat semolina used for making upma, halwa, and savory snacks.",
    image: productImages[9],
    nutrition: {
      calories: 120,
      protein: 3.5,
      carbs: 23,
      fat: 0.3,
    },
    tags: ["semolina", "staple", "indian", "baking"],
    inStock: true,
  },
  {
    id: "p022",
    name: "Besan (Gram Flour)",
    category: "Staples",
    price: 75,
    description: "Fine chickpea flour used for making pakoras, bhajis, and sweets.",
    image: productImages[9],
    nutrition: {
      calories: 120,
      protein: 6,
      carbs: 21,
      fat: 1.2,
    },
    tags: ["flour", "staple", "indian", "baking"],
    inStock: true,
  },
  {
    id: "p023",
    name: "Poha (Flattened Rice)",
    category: "Staples",
    price: 55,
    description: "Flattened rice flakes for quick breakfast preparations and snacks.",
    image: productImages[9],
    nutrition: {
      calories: 110,
      protein: 2.2,
      carbs: 24,
      fat: 0.2,
    },
    tags: ["rice", "staple", "indian", "breakfast"],
    inStock: true,
  },
  {
    id: "p024",
    name: "Moong Dal (Yellow Split Gram)",
    category: "Pulses",
    price: 85,
    description: "Split yellow lentils that cook quickly and are easily digestible.",
    image: productImages[10],
    nutrition: {
      calories: 105,
      protein: 7,
      carbs: 18,
      fat: 0.5,
    },
    tags: ["dal", "lentils", "protein", "indian", "pulses"],
    inStock: true,
  },
  {
    id: "p025",
    name: "Urad Dal (Black Gram)",
    category: "Pulses",
    price: 95,
    description: "Split black gram used for making dosas, idlis, and dal preparations.",
    image: productImages[10],
    nutrition: {
      calories: 115,
      protein: 7.5,
      carbs: 20,
      fat: 0.6,
    },
    tags: ["dal", "lentils", "protein", "indian", "pulses"],
    inStock: true,
  },
  {
    id: "p026",
    name: "Rajma (Kidney Beans)",
    category: "Pulses",
    price: 125,
    description: "Red kidney beans for making the popular North Indian curry, Rajma.",
    image: productImages[10],
    nutrition: {
      calories: 125,
      protein: 8.5,
      carbs: 22.5,
      fat: 0.5,
    },
    tags: ["beans", "protein", "indian", "pulses"],
    inStock: true,
  },
  {
    id: "p027",
    name: "Cumin Seeds",
    category: "Spices",
    price: 65,
    description: "Aromatic cumin seeds used as a base for many Indian dishes.",
    image: productImages[14],
    nutrition: {
      calories: 8,
      protein: 0.4,
      carbs: 1,
      fat: 0.5,
    },
    tags: ["spices", "indian", "seeds", "tempering"],
    inStock: true,
  },
  {
    id: "p028",
    name: "Green Cardamom",
    category: "Spices",
    price: 185,
    description: "Aromatic green cardamom pods used in both sweet and savory dishes.",
    image: productImages[14],
    nutrition: {
      calories: 6,
      protein: 0.2,
      carbs: 1.1,
      fat: 0.1,
    },
    tags: ["spices", "indian", "aromatic", "dessert"],
    inStock: true,
  },
  {
    id: "p029",
    name: "Cinnamon Sticks",
    category: "Spices",
    price: 110,
    description: "Aromatic cinnamon sticks for flavoring biryanis, curries, and desserts.",
    image: productImages[14],
    nutrition: {
      calories: 6,
      protein: 0.1,
      carbs: 2,
      fat: 0.1,
    },
    tags: ["spices", "indian", "aromatic", "dessert"],
    inStock: true,
  },
  {
    id: "p030",
    name: "Red Chili Powder",
    category: "Spices",
    price: 60,
    description: "Ground red chili powder for adding heat to dishes.",
    image: productImages[8],
    nutrition: {
      calories: 8,
      protein: 0.3,
      carbs: 1.3,
      fat: 0.4,
    },
    tags: ["spices", "indian", "hot", "seasoning"],
    inStock: true,
  },
  {
    id: "p031",
    name: "Coriander Powder",
    category: "Spices",
    price: 45,
    description: "Ground coriander seeds adding a warm, nutty flavor to dishes.",
    image: productImages[8],
    nutrition: {
      calories: 7,
      protein: 0.3,
      carbs: 1.2,
      fat: 0.3,
    },
    tags: ["spices", "indian", "seasoning", "aromatic"],
    inStock: true,
  },
  {
    id: "p032",
    name: "Mustard Oil",
    category: "Oils & Condiments",
    price: 165,
    description: "Pungent mustard oil used in East Indian and Bengali cuisine.",
    image: productImages[12],
    nutrition: {
      calories: 120,
      protein: 0,
      carbs: 0,
      fat: 14,
    },
    tags: ["oil", "cooking", "indian", "bengali"],
    inStock: true,
  },
  {
    id: "p033",
    name: "Sesame Oil",
    category: "Oils & Condiments",
    price: 225,
    description: "Aromatic sesame oil used for tempering and flavoring South Indian dishes.",
    image: productImages[12],
    nutrition: {
      calories: 120,
      protein: 0,
      carbs: 0,
      fat: 14,
    },
    tags: ["oil", "cooking", "indian", "south indian"],
    inStock: true,
  },
  {
    id: "p034",
    name: "Rock Salt (Sendha Namak)",
    category: "Staples",
    price: 35,
    description: "Unrefined rock salt used in fasting (vrat) dishes and for therapeutic purposes.",
    image: productImages[9],
    nutrition: {
      calories: 0,
      protein: 0,
      carbs: 0,
      fat: 0,
    },
    tags: ["salt", "staple", "fasting", "seasoning"],
    inStock: true,
  },
  {
    id: "p035",
    name: "Jaggery (Gur)",
    category: "Staples",
    price: 65,
    description: "Traditional unrefined sugar with a rich molasses flavor, used in sweets and savory dishes.",
    image: productImages[9],
    nutrition: {
      calories: 38,
      protein: 0.1,
      carbs: 9.8,
      fat: 0,
    },
    tags: ["sugar", "sweetener", "indian", "natural"],
    inStock: true,
  },
  {
    id: "p036",
    name: "Instant Coffee",
    category: "Beverages",
    price: 245,
    description: "Premium instant coffee for a quick and aromatic caffeine boost.",
    image: productImages[15],
    nutrition: {
      calories: 2,
      protein: 0.1,
      carbs: 0.5,
      fat: 0,
    },
    tags: ["coffee", "caffeine", "beverage", "instant"],
    inStock: true,
  },
  {
    id: "p037",
    name: "Green Tea",
    category: "Beverages",
    price: 175,
    description: "Delicate green tea leaves rich in antioxidants and subtle flavor.",
    image: productImages[15],
    nutrition: {
      calories: 1,
      protein: 0,
      carbs: 0.2,
      fat: 0,
    },
    tags: ["tea", "beverages", "healthy", "antioxidant"],
    inStock: true,
  },
  {
    id: "p038",
    name: "Cashews",
    category: "Dry Fruits & Nuts",
    price: 450,
    description: "Premium whole cashew nuts for snacking and cooking.",
    image: productImages[0],
    nutrition: {
      calories: 160,
      protein: 5,
      carbs: 9,
      fat: 13,
    },
    tags: ["nuts", "snack", "protein", "healthy"],
    inStock: true,
  },
  {
    id: "p039",
    name: "Almonds",
    category: "Dry Fruits & Nuts",
    price: 475,
    description: "Raw almonds rich in healthy fats, protein, and nutrients.",
    image: productImages[0],
    nutrition: {
      calories: 170,
      protein: 6,
      carbs: 6,
      fat: 15,
    },
    tags: ["nuts", "snack", "protein", "healthy"],
    inStock: true,
  },
  {
    id: "p040",
    name: "Ginger Garlic Paste",
    category: "Condiments",
    price: 60,
    description: "Ready-to-use paste of fresh ginger and garlic, a base for many Indian dishes.",
    image: productImages[13],
    nutrition: {
      calories: 15,
      protein: 0.6,
      carbs: 3,
      fat: 0.1,
    },
    tags: ["condiment", "paste", "indian", "cooking"],
    inStock: true,
  },
  {
    id: "p041",
    name: "Pickle (Mixed Vegetable)",
    category: "Condiments",
    price: 95,
    description: "Spicy mixed vegetable pickle to accompany meals.",
    image: productImages[13],
    nutrition: {
      calories: 30,
      protein: 0.5,
      carbs: 3,
      fat: 2,
    },
    tags: ["pickle", "condiment", "spicy", "indian"],
    inStock: true,
  },
  {
    id: "p042",
    name: "Maggi Noodles",
    category: "Ready-Made",
    price: 15,
    description: "Popular instant noodles ready in just 2 minutes.",
    image: productImages[2],
    nutrition: {
      calories: 180,
      protein: 4,
      carbs: 25,
      fat: 8,
    },
    tags: ["instant", "noodles", "quick", "snack"],
    inStock: true,
  },
  {
    id: "p043",
    name: "Papad",
    category: "Ready-Made",
    price: 45,
    description: "Thin, crisp rounds made from lentil flour, ready to roast or fry.",
    image: productImages[2],
    nutrition: {
      calories: 50,
      protein: 2,
      carbs: 8,
      fat: 1,
    },
    tags: ["ready-to-cook", "snack", "indian", "crispy"],
    inStock: true,
  },
  {
    id: "p044",
    name: "Maida (Refined Flour)",
    category: "Staples",
    price: 45,
    description: "Fine, refined wheat flour ideal for making naan, pastries, and various sweet dishes.",
    image: productImages[9],
    nutrition: {
      calories: 110,
      protein: 3,
      carbs: 23,
      fat: 0.2,
    },
    tags: ["flour", "staple", "baking", "indian"],
    inStock: true,
  },
  {
    id: "p045",
    name: "Rice Flour",
    category: "Staples",
    price: 60,
    description: "Finely ground rice flour used for making dosas, noodles, and gluten-free preparations.",
    image: productImages[9],
    nutrition: {
      calories: 110,
      protein: 1.5,
      carbs: 24,
      fat: 0.2,
    },
    tags: ["flour", "gluten-free", "staple", "indian"],
    inStock: true,
  },
  {
    id: "p046",
    name: "Corn Flour",
    category: "Staples",
    price: 55,
    description: "Fine yellow corn flour used as a thickening agent and for making corn tortillas.",
    image: productImages[9],
    nutrition: {
      calories: 110,
      protein: 2.5,
      carbs: 24,
      fat: 0.4,
    },
    tags: ["flour", "gluten-free", "thickener", "baking"],
    inStock: true,
  },
  {
    id: "p047",
    name: "Sabudana (Tapioca Pearls)",
    category: "Staples",
    price: 85,
    description: "White tapioca pearls used in fasting dishes, khichdi, and desserts.",
    image: productImages[9],
    nutrition: {
      calories: 130,
      protein: 0.3,
      carbs: 32,
      fat: 0.1,
    },
    tags: ["fasting", "staple", "tapioca", "indian"],
    inStock: true,
  },
  {
    id: "p048",
    name: "Masoor Dal (Red Lentils)",
    category: "Pulses",
    price: 95,
    description: "Split red lentils that cook quickly and are perfect for soups and light curries.",
    image: productImages[10],
    nutrition: {
      calories: 105,
      protein: 8,
      carbs: 18,
      fat: 0.4,
    },
    tags: ["dal", "lentils", "protein", "indian", "pulses"],
    inStock: true,
  },
  {
    id: "p049",
    name: "Kabuli Chana (Chickpeas)",
    category: "Pulses",
    price: 140,
    description: "Large white chickpeas used in chole, salads, and hummus preparations.",
    image: productImages[10],
    nutrition: {
      calories: 120,
      protein: 7.5,
      carbs: 20,
      fat: 2,
    },
    tags: ["chickpeas", "protein", "pulses", "indian"],
    inStock: true,
  },
  {
    id: "p050",
    name: "Fennel Seeds",
    category: "Spices",
    price: 75,
    description: "Aromatic fennel seeds with a sweet licorice flavor, used in both savory dishes and as a mouth freshener.",
    image: productImages[14],
    nutrition: {
      calories: 7,
      protein: 0.4,
      carbs: 1.2,
      fat: 0.3,
    },
    tags: ["spices", "indian", "seeds", "digestive"],
    inStock: true,
  },
  {
    id: "p051",
    name: "Fenugreek Seeds",
    category: "Spices",
    price: 45,
    description: "Slightly bitter seeds used in pickling, curry powders, and many spice blends.",
    image: productImages[14],
    nutrition: {
      calories: 6,
      protein: 0.3,
      carbs: 1,
      fat: 0.2,
    },
    tags: ["spices", "indian", "seeds", "aromatic"],
    inStock: true,
  },
  {
    id: "p052",
    name: "Carom Seeds (Ajwain)",
    category: "Spices",
    price: 60,
    description: "Aromatic seeds with a thyme-like flavor, used in breads and digestive remedies.",
    image: productImages[14],
    nutrition: {
      calories: 6,
      protein: 0.4,
      carbs: 1.1,
      fat: 0.3,
    },
    tags: ["spices", "indian", "seeds", "digestive"],
    inStock: true,
  },
  {
    id: "p053",
    name: "Chaat Masala",
    category: "Spices",
    price: 65,
    description: "Tangy spice blend used to flavor street foods, salads, and snacks.",
    image: productImages[8],
    nutrition: {
      calories: 7,
      protein: 0.3,
      carbs: 1.2,
      fat: 0.2,
    },
    tags: ["spices", "indian", "blend", "tangy"],
    inStock: true,
  },
  {
    id: "p054",
    name: "Sambar Powder",
    category: "Spices",
    price: 75,
    description: "South Indian spice blend for making traditional sambar and other dishes.",
    image: productImages[8],
    nutrition: {
      calories: 8,
      protein: 0.4,
      carbs: 1.4,
      fat: 0.3,
    },
    tags: ["spices", "south indian", "blend", "curry"],
    inStock: true,
  },
  {
    id: "p055",
    name: "Kasuri Methi (Dried Fenugreek Leaves)",
    category: "Spices",
    price: 65,
    description: "Dried fenugreek leaves with a distinctive aroma, used in curries and naan.",
    image: productImages[13],
    nutrition: {
      calories: 5,
      protein: 0.5,
      carbs: 0.9,
      fat: 0.1,
    },
    tags: ["spices", "indian", "herb", "aromatic"],
    inStock: true,
  },
  {
    id: "p056",
    name: "Groundnut Oil",
    category: "Oils & Condiments",
    price: 195,
    description: "Light oil made from peanuts, popular in South and Western Indian cooking.",
    image: productImages[12],
    nutrition: {
      calories: 120,
      protein: 0,
      carbs: 0,
      fat: 14,
    },
    tags: ["oil", "cooking", "indian", "peanut"],
    inStock: true,
  },
  {
    id: "p057",
    name: "Sunflower Oil",
    category: "Oils & Condiments",
    price: 150,
    description: "Light, all-purpose cooking oil with a neutral flavor.",
    image: productImages[12],
    nutrition: {
      calories: 120,
      protein: 0,
      carbs: 0,
      fat: 14,
    },
    tags: ["oil", "cooking", "neutral", "all-purpose"],
    inStock: true,
  },
  {
    id: "p058",
    name: "Raisins",
    category: "Dry Fruits & Nuts",
    price: 130,
    description: "Sweet, dried grapes used in desserts, biryanis, and as a healthy snack.",
    image: productImages[0],
    nutrition: {
      calories: 85,
      protein: 0.9,
      carbs: 22,
      fat: 0.1,
    },
    tags: ["dry fruits", "sweet", "dessert", "snack"],
    inStock: true,
  },
  {
    id: "p059",
    name: "Dates",
    category: "Dry Fruits & Nuts",
    price: 210,
    description: "Sweet, nutrient-rich dates that serve as a natural sweetener or healthy snack.",
    image: productImages[0],
    nutrition: {
      calories: 90,
      protein: 0.8,
      carbs: 24,
      fat: 0.1,
    },
    tags: ["dry fruits", "sweet", "natural", "energy"],
    inStock: true,
  },
  {
    id: "p060",
    name: "Tamarind Paste",
    category: "Condiments",
    price: 120,
    description: "Concentrated paste made from tamarind fruit, adding sour notes to dishes.",
    image: productImages[13],
    nutrition: {
      calories: 25,
      protein: 0.3,
      carbs: 6,
      fat: 0.1,
    },
    tags: ["condiment", "sour", "indian", "paste"],
    inStock: true,
  },
  {
    id: "p061",
    name: "Tomato Ketchup",
    category: "Condiments",
    price: 85,
    description: "Classic tomato sauce for use with snacks, sandwiches, and as a cooking ingredient.",
    image: productImages[13],
    nutrition: {
      calories: 20,
      protein: 0.2,
      carbs: 5,
      fat: 0,
    },
    tags: ["condiment", "sauce", "tomato", "snack"],
    inStock: true,
  },
  {
    id: "p062",
    name: "Vinegar",
    category: "Condiments",
    price: 65,
    description: "Distilled white vinegar for pickling, chutneys, and various culinary uses.",
    image: productImages[1],
    nutrition: {
      calories: 3,
      protein: 0,
      carbs: 0.1,
      fat: 0,
    },
    tags: ["condiment", "sour", "preservative", "cooking"],
    inStock: true,
  },
  {
    id: "p063",
    name: "Mayonnaise",
    category: "Condiments",
    price: 110,
    description: "Creamy sandwich spread and dressing made with eggs and oil.",
    image: productImages[1],
    nutrition: {
      calories: 95,
      protein: 0.2,
      carbs: 0.4,
      fat: 10,
    },
    tags: ["condiment", "sauce", "creamy", "sandwich"],
    inStock: true,
  },
];

// Function to get recommended products based on an item
export const getRecommendedProducts = (item: Product): Product[] => {
  // In a real app, this would use AI algorithm, but for now:
  // Return products that share at least one tag with the given item
  const similarItems = products.filter(
    (product) => 
      product.id !== item.id && 
      product.tags.some(tag => item.tags.includes(tag))
  );
  
  return similarItems.slice(0, 3);
};

// Function to search products
export const searchProducts = (query: string): Product[] => {
  if (!query.trim()) return products;
  
  const lowercaseQuery = query.toLowerCase();
  
  return products.filter(
    (product) => 
      product.name.toLowerCase().includes(lowercaseQuery) ||
      product.description.toLowerCase().includes(lowercaseQuery) ||
      product.category.toLowerCase().includes(lowercaseQuery) ||
      product.tags.some(tag => tag.toLowerCase().includes(lowercaseQuery))
  );
};
